### ISSUE TITLE
Link crash with master

### ISSUE THREAD

**Issue by cjb** [erming/shout#322]
Running 0.49.0:

```
/home/ubuntu/shout/src/plugins/irc-events/link.js:120
                                type: req.response.headers['content-type'].split(/ *; */).shift()
                                                                           ^
TypeError: Cannot call method 'split' of undefined
    at /home/ubuntu/shout/src/plugins/irc-events/link.js:120:48
    at Stream.<anonymous> (/home/ubuntu/shout/node_modules/event-stream/index.js:303:20)
    at _end (/home/ubuntu/shout/node_modules/event-stream/node_modules/through/index.js:65:9)
    at Stream.stream.end (/home/ubuntu/shout/node_modules/event-stream/node_modules/through/index.js:74:5)
    at Stream.onend (stream.js:79:10)
    at Stream.EventEmitter.emit (events.js:117:20)
    at end (/home/ubuntu/shout/node_modules/event-stream/node_modules/map-stream/index.js:116:39)
    at Stream.stream.end (/home/ubuntu/shout/node_modules/event-stream/node_modules/map-stream/index.js:122:5)
    at Request.onend (stream.js:79:10)
    at Request.EventEmitter.emit (events.js:117:20)
```

**Comment by linux4kix** [comment]
@cjb Funny to see you here.  I had fixed this last weekend and just got around to pushing issuing a pull request.  With this fixed shout has been running on my server all week without any issues.

**Comment by erming** [comment]
Hey, this shouldn't be a problem anymore. (I merged this one: https://github.com/erming/shout/pull/329, thanks @linux4kix!)
