### ISSUE TITLE
Link crash with master, invalid URI

### ISSUE THREAD

**Issue by cjb** [erming/shout#324]
Looks like a bad URL was seen in chat, need to catch these instead of letting them crash the server.

```
Error: Invalid URI "https:///"
    at Request.init (/home/ubuntu/shout/node_modules/request/request.js:443:31)
    at new Request (/home/ubuntu/shout/node_modules/request/request.js:283:8)
    at request (/home/ubuntu/shout/node_modules/request/index.js:50:10)
    at Function.request.get (/home/ubuntu/shout/node_modules/request/index.js:63:27)
    at fetch (/home/ubuntu/shout/src/plugins/irc-events/link.js:92:20)
    at Client.<anonymous> (/home/ubuntu/shout/src/plugins/irc-events/link.js:46:3)
    at Client.EventEmitter.emit (events.js:117:20)
    at Client.<anonymous> (/home/ubuntu/shout/node_modules/slate-irc/lib/plugins/privmsg.js:23:11)
    at Client.EventEmitter.emit (events.js:117:20)
    at Client.onmessage (/home/ubuntu/shout/node_modules/slate-irc/index.js:355:8)
```

**Comment by erming** [comment]
Thanks for noticing this!

I should've been more careful and done some more testing when merging a PR that changed the library used for pulling links (related: https://github.com/erming/shout/pull/315).

I've fixed this and published it as version `0.49.2`.
