### ISSUE TITLE
Crash on malformed URLs

### ISSUE THREAD

**Issue by codl** [erming/shout#331]
If someone posts a malformed URL like `http:///`, shout crashes with

    Error: Invalid URI "http:///"
        at Request.init (/usr/local/lib/node_modules/shout/node_modules/request/request.js:443:31)
        at new Request (/usr/local/lib/node_modules/shout/node_modules/request/request.js:283:8)
        at request (/usr/local/lib/node_modules/shout/node_modules/request/index.js:50:10)
        at Function.request.get (/usr/local/lib/node_modules/shout/node_modules/request/index.js:63:27)
        at fetch (/usr/local/lib/node_modules/shout/src/plugins/irc-events/link.js:92:20)
        at Client.<anonymous> (/usr/local/lib/node_modules/shout/src/plugins/irc-events/link.js:46:3)
        at Client.EventEmitter.emit (events.js:117:20)
        at Client.<anonymous> (/usr/local/lib/node_modules/shout/node_modules/slate-irc/lib/plugins/privmsg.js:23:11)
        at Client.EventEmitter.emit (events.js:117:20)
        at Client.onmessage (/usr/local/lib/node_modules/shout/node_modules/slate-irc/index.js:355:8)

**Comment by erming** [comment]
Hey @codl; this should've been solved in the latest version. Please update via `npm -g update shout`.

 Report back if the problem persists!

**Comment by codl** [comment]
Yup it's fixed! Thanks!
