### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by shadowfacts** [erming/shout#360]
Every time I try to start shout it crashes with this error message:
```
Shout is now running on http://0.0.0.0:80/
Press ctrl-c to stop

User 'shadowfacts' loaded.
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: listen EACCES
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1112:19)
    at listen (net.js:1155:10)
    at net.js:1253:9
    at dns.js:85:18
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3
```

I cannot for the love of me figure out what the problem is.

**Comment by shadowfacts** [comment]
nvm, realized I was trying to run it on port 80 when [my website](http://shadowfacts.net) was already running on port 80.
