### ISSUE TITLE
Casual memory leak

### ISSUE THREAD

**Issue by CromFr** [erming/shout#396]
Regulary, shout logs possible memory leaks, leading to either the process being killed by the OS or a server disconnection.
I have only 1 user on shout (CromFr) which connects to freenode irc

I'm running shout on a Archlinux VPS, with node v0.12.1

Detailed logs:
```
Mar 31 14:39:06: pam_unix(su:session): session opened for user shout by (uid=0)
Mar 31 14:39:08: Shout is now running on http://127.0.0.1:9000/
Mar 31 14:39:08: Press ctrl-c to stop
Mar 31 14:39:08: User 'CromFr' loaded.
Mar 31 16:48:29: (node) warning: possible EventEmitter memory leak detected. 11 end listeners added
Mar 31 16:48:29: Trace
Mar 31 16:48:29: at Request.addListener (events.js:179:15)
Mar 31 16:48:29: at Request.onRequestResponse (/usr/lib/node_modules/shout/node_modules/request/req
Mar 31 16:48:29: at ClientRequest.emit (events.js:107:17)
Mar 31 16:48:29: at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:419:21)
Mar 31 16:48:29: at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)
Mar 31 16:48:29: at TLSSocket.socketOnData (_http_client.js:310:20)
Mar 31 16:48:29: at TLSSocket.emit (events.js:107:17)
Mar 31 16:48:29: at readableAddChunk (_stream_readable.js:163:16)
Mar 31 16:48:29: at TLSSocket.Readable.push (_stream_readable.js:126:10)
Mar 31 16:48:29: at TCP.onread (net.js:529:20)
Apr 06 02:00:04: (node) warning: possible EventEmitter memory leak detected. 11 end listeners added
Apr 06 02:00:04: Trace
Apr 06 02:00:04: at Request.addListener (events.js:179:15)
Apr 06 02:00:04: at Request.start (/usr/lib/node_modules/shout/node_modules/request/request.js:947:
Apr 06 02:00:04: at Request.end (/usr/lib/node_modules/shout/node_modules/request/request.js:1732:1
Apr 06 02:00:04: at end (/usr/lib/node_modules/shout/node_modules/request/request.js:704:14)
Apr 06 02:00:04: at Immediate._onImmediate (/usr/lib/node_modules/shout/node_modules/request/reques
Apr 06 02:00:04: at processImmediate [as _immediateCallback] (timers.js:358:17)
Apr 06 02:00:05: (node) warning: possible EventEmitter memory leak detected. 11 pipe listeners adde
Apr 06 02:00:05: Trace
Apr 06 02:00:05: at Request.addListener (events.js:179:15)
Apr 06 02:00:05: at Request.init (/usr/lib/node_modules/shout/node_modules/request/request.js:646:8
Apr 06 02:00:05: at Request.onRequestResponse (/usr/lib/node_modules/shout/node_modules/request/req
Apr 06 02:00:05: at ClientRequest.emit (events.js:107:17)
Apr 06 02:00:05: at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:419:21)
Apr 06 02:00:05: at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)
Apr 06 02:00:05: at TLSSocket.socketOnData (_http_client.js:310:20)
Apr 06 02:00:05: at TLSSocket.emit (events.js:107:17)
Apr 06 02:00:05: at readableAddChunk (_stream_readable.js:163:16)
Apr 06 02:00:05: at TLSSocket.Readable.push (_stream_readable.js:126:10)
Apr 08 22:37:37: Killed


Mar 22 12:32:47: Shout is now running on http://127.0.0.1:9000/
Mar 22 12:32:47: Press ctrl-c to stop
Mar 22 12:32:47: User 'CromFr' loaded.
Mar 23 21:16:22: (node) warning: possible EventEmitter memory leak detected. 11 end listeners adde
Mar 23 21:16:22: Trace
Mar 23 21:16:22: at Request.addListener (events.js:179:15)
Mar 23 21:16:22: at Request.start (/usr/lib/node_modules/shout/node_modules/request/request.js:947
Mar 23 21:16:22: at Request.end (/usr/lib/node_modules/shout/node_modules/request/request.js:1732:
Mar 23 21:16:22: at end (/usr/lib/node_modules/shout/node_modules/request/request.js:704:14)
Mar 23 21:16:22: at Immediate._onImmediate (/usr/lib/node_modules/shout/node_modules/request/reque
Mar 23 21:16:22: at processImmediate [as _immediateCallback] (timers.js:358:17)
Mar 24 21:29:07: (node) warning: possible EventEmitter memory leak detected. 11 end listeners adde
Mar 24 21:29:07: Trace
Mar 24 21:29:07: at Request.addListener (events.js:179:15)
Mar 24 21:29:07: at Request.start (/usr/lib/node_modules/shout/node_modules/request/request.js:947
Mar 24 21:29:07: at Request.end (/usr/lib/node_modules/shout/node_modules/request/request.js:1732:
Mar 24 21:29:07: at end (/usr/lib/node_modules/shout/node_modules/request/request.js:704:14)
Mar 24 21:29:07: at Immediate._onImmediate (/usr/lib/node_modules/shout/node_modules/request/reque
Mar 24 21:29:07: at processImmediate [as _immediateCallback] (timers.js:358:17)
Mar 24 21:29:09: (node) warning: possible EventEmitter memory leak detected. 11 pipe listeners add
Mar 24 21:29:09: Trace
Mar 24 21:29:09: at Request.addListener (events.js:179:15)
Mar 24 21:29:09: at Request.init (/usr/lib/node_modules/shout/node_modules/request/request.js:646:
Mar 24 21:29:09: at Request.onRequestResponse (/usr/lib/node_modules/shout/node_modules/request/re
Mar 24 21:29:09: at ClientRequest.emit (events.js:107:17)
Mar 24 21:29:09: at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:419:21)
Mar 24 21:29:09: at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)
Mar 24 21:29:09: at Socket.socketOnData (_http_client.js:310:20)
Mar 24 21:29:09: at Socket.emit (events.js:107:17)
Mar 24 21:29:09: at readableAddChunk (_stream_readable.js:163:16)
Mar 24 21:29:09: at Socket.Readable.push (_stream_readable.js:126:10)
Mar 27 10:20:36: Client#connect():
Mar 27 10:20:36: Error: This socket has been ended by the other party
```

**Comment by erming** [comment]
Looks like someone is posting a link (or links) that crashes Shout by provoking some kind of bug in the `request.js` library.

Open your config and turn this feature off:
https://github.com/erming/shout/blob/master/defaults/config.js#L65

We've tried several of the HTTP request libraries (we're currently using `request.js`), but there's always some weird edge-case or kind of links that doesn't work. Ugh. Sorry 'bout that.

I might end up removing this feature, I don't think it's that useful anyway.

Thanks for reporting.

**Comment by aynik** [comment]
+1. Deactivating it was the first thing I did, it hurts privacy.

**Comment by erming** [comment]
This problem have now been fixed. Update to `0.51.1` to get the latest update.

It turns out it wasn't really a bug. If you were having multiple users/lots of channel, and people post alot of links, the events waiting for links to responed might become too many and throw that exception.

This was solved by allowing unlimited event listeners.
Related: https://github.com/erming/shout/blob/master/src/plugins/irc-events/link.js#L8

This problem never occured for me, so thanks for reporting in, @CromFr!

Closing the issue..

**Comment by erming** [comment]
Argh.. My demo instance just crashed. The problem is still there.
While it's better than before, it still might crash the program. It seems that some links might send the request.js-client into a redirect loop, which will crash it.

We're not the only ones experiencing this problem: https://github.com/request/request/issues/311

I'll see what I can do about it.
Crashing is unacceptable, so it's definitely something I want to fix ASAP.

**Comment by CromFr** [comment]
great to see you are working hard to fix this issue :)

**Comment by mildused** [comment]
Does disabling prefetch resolve this issue?
