### ISSUE TITLE
Feature Request :identd server

### ISSUE THREAD

**Issue by tracker1** [erming/shout#415]
It would be relatively easy for the server to know the client IP, and if there's a server-side login who that user is to respond to IDENTD port/requests...

The protocol is pretty easy at that.  I would suggest exposing the client's actual IP address connecting to the website as part of the user's name.

**Comment by erming** [comment]
Hey man!

Good news!
This  feature is already implemented.

Open your config and set this value to `true` and restart your Shout server: https://github.com/erming/shout/blob/master/defaults/config.js#L240

Get back to me if it doesn't work.

**Comment by Jnbond** [comment]
Hello,
First of all congratulations for your work!

I put the parameter is "true" and here's the result in consol when I run the server :

===========================================================================
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: listen EACCES
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1129:19)
    at listen (net.js:1172:10)
    at Server.listen (net.js:1257:5)
    at Object.module.exports.start (/usr/local/lib/node_modules/shout/src/identd.js:7:38)
    at module.exports (/usr/local/lib/node_modules/shout/src/server.js:43:23)
    at Command.<anonymous> (/usr/local/lib/node_modules/shout/src/command-line/start.js:30:4)
    at Command.listener (/usr/local/lib/node_modules/shout/node_modules/commander/index.js:301:8)
    at Command.emit (events.js:110:17)
    at Command.parseArgs (/usr/local/lib/node_modules/shout/node_modules/commander/index.js:610:12)
===========================================================================

P.S: sorry for my bad english, I'm french
