### ISSUE TITLE
RangeError: Invalid string length

### ISSUE THREAD

**Issue by farcaller** [erming/shout#422]
Crashed at:

```javascript
/tmp/shout/node_modules/socket.io/node_modules/engine.io/node_modules/engine.io-parser/lib/index.js:433
      strLen += '' + bufferTail[i];
              ^
RangeError: Invalid string length
    at Object.exports.decodePayloadAsBinary (/tmp/shout/node_modules/socket.io/node_modules/engine.io/node_modules/engine.io-parser/lib/index.js:433:20)
    at Object.exports.decodePayload (/tmp/shout/node_modules/socket.io/node_modules/engine.io/node_modules/engine.io-parser/lib/index.js:271:20)
    at XHR.Polling.onData (/tmp/shout/node_modules/socket.io/node_modules/engine.io/lib/transports/polling.js:196:10)
    at IncomingMessage.onEnd (/tmp/shout/node_modules/socket.io/node_modules/engine.io/lib/transports/polling.js:158:10)
    at IncomingMessage.emit (events.js:104:17)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```

**Comment by trh-x** [comment]
Just had exactly the same crash...
