### ISSUE TITLE
dns.js error

### ISSUE THREAD

**Issue by TuSuNaMi** [erming/shout#448]
Shout is now running on http://0.0.0.0:3000/
Press ctrl-c to stop

dns.js:156
      throw errnoException(process._errno, bindingName);
            ^
Error: getHostByAddr ENOTIMP
    at errnoException (dns.js:37:11)
    at Object.query [as reverse] (dns.js:156:13)
    at init (/root/shout/src/server.js:96:7)
    at Socket.auth (/root/shout/src/server.js:156:3)
    at Namespace.<anonymous> (/root/shout/src/server.js:53:9)
    at Namespace.emit (events.js:95:17)
    at Namespace.emit (/root/shout/node_modules/socket.io/lib/namespace.js:205:10)
    at /root/shout/node_modules/socket.io/lib/namespace.js:171:14
    at process._tickCallback (node.js:442:13)
npm ERR! weird error 8
npm ERR! not ok code 0

**Comment by TuSuNaMi** [comment]
Solved with patch

**Comment by kathir04on** [comment]
I got same issue... Can you please help me... How to resolved ?

**Comment by dgw** [comment]
@kathir04on It's been 3 years since this issue, and Shout is no longer developed. I suggest switching to [The Lounge](https://github.com/thelounge/thelounge), an actively maintained fork of Shout. (TL is coming up on version 3.0, with a bunch of new features.)
