### ISSUE TITLE
`whowas` crashes Shout..

### ISSUE THREAD

**Issue by pirogoeth** [erming/shout#531]
After executing a `/quote whowas <nick>` through Shout, the server crashed throwing this traceback:
```
/usr/local/lib/node_modules/shout/node_modules/slate-irc/lib/plugins/whois.js:58
          map[target].server = params[2];
                             ^
TypeError: Cannot set property 'server' of undefined
    at Client.<anonymous> (/usr/local/lib/node_modules/shout/node_modules/slate-irc/lib/plugins/whois.js:58:30)
    at Client.emit (events.js:129:20)
    at Client.onmessage (/usr/local/lib/node_modules/shout/node_modules/slate-irc/index.js:355:8)
    at Parser.emit (events.js:107:17)
    at Parser.online (/usr/local/lib/node_modules/shout/node_modules/slate-irc/node_modules/slate-irc-parser/index.js:88:8)
    at Stream.emit (events.js:107:17)
    at pushData (/usr/local/lib/node_modules/shout/node_modules/slate-irc/node_modules/slate-irc-parser/node_modules/linewise/lib/linewise.js:98:10)
    at Stream.write (/usr/local/lib/node_modules/shout/node_modules/slate-irc/node_modules/slate-irc-parser/node_modules/linewise/lib/linewise.js:62:16)
    at Parser.write (/usr/local/lib/node_modules/shout/node_modules/slate-irc/node_modules/slate-irc-parser/index.js:45:24)
    at TLSSocket.ondata (_stream_readable.js:540:20)
```

There was a slightly different traceback from the first time I ran a `/quote whowas`:
```
/usr/local/lib/node_modules/shout/node_modules/slate-irc/lib/plugins/whois.js:87
          if (target !== 'whois') return;
                     ^
TypeError: Cannot set property 'server' of undefined
    at Client.<anonymous> (/usr/local/lib/node_modules/shout/node_modules/slate-irc/lib/plugins/whois.js:58:30)
    at Client.emit (events.js:129:20)
    at Client.onmessage (/usr/local/lib/node_modules/shout/node_modules/slate-irc/index.js:355:8)
    at Parser.emit (events.js:107:17)
    at Parser.online (/usr/local/lib/node_modules/shout/node_modules/slate-irc/node_modules/slate-irc-parser/index.js:88:8)
    at Stream.emit (events.js:107:17)
    at pushData (/usr/local/lib/node_modules/shout/node_modules/slate-irc/node_modules/slate-irc-parser/node_modules/linewise/lib/linewise.js:98:10)
    at Stream.write (/usr/local/lib/node_modules/shout/node_modules/slate-irc/node_modules/slate-irc-parser/node_modules/linewise/lib/linewise.js:62:16)
    at Parser.write (/usr/local/lib/node_modules/shout/node_modules/slate-irc/node_modules/slate-irc-parser/index.js:45:24)
    at TLSSocket.ondata (_stream_readable.js:540:20)
```

**Comment by Wharenn** [comment]
I have the same bug, but it seems related to the underlying Slate IRC dependency, and not shout itself. I opened an issue in slate-irc repo.
