### ISSUE TITLE
Shout Cannon Start

### ISSUE THREAD

**Issue by xnaas** [erming/shout#650]
I'm sure I'm the one doing something wrong, but I'm at a loss here. I install shout but every time upon running it, I immediately get this:

```
xnaas@xnaasUB:~/shout$ npm start

> shout@0.53.0 start /home/xnaas/shout
> node index


Shout is now running on http://0.0.0.0:49409/
Press ctrl-c to stop

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 0.0.0.0:49409
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at Server._listen2 (net.js:1237:14)
    at listen (net.js:1273:10)
    at net.js:1382:9
    at nextTickCallbackWith3Args (node.js:452:9)
    at process._tickCallback (node.js:358:17)
    at Function.Module.runMain (module.js:444:11)
    at startup (node.js:136:18)
    at node.js:966:3

npm ERR! Linux 3.19.0-49-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.3.0
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! shout@0.53.0 start: `node index`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the shout@0.53.0 start script 'node index'.
npm ERR! This is most likely a problem with the shout package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index
npm ERR! You can get their info via:
npm ERR!     npm owner ls shout
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/xnaas/shout/npm-debug.log
xnaas@xnaasUB:~/shout$
```

Please help me understand what's going wrong.

**Comment by MaxLeiter** [comment]
is it possible you’re already running an instance of shout on that port?

**Comment by xnaas** [comment]
Shout shouldn't be running at all. Is it possible to check?

**Comment by xnaas** [comment]
Also, I've tried overriding with numerous different ports with no luck.

**Comment by xnaas** [comment]
Wait. I was able to get it working. Turns out ZNC was trying to use the same port and hadn't actually shut down. No idea why other ports weren't working, but whatever. :)
