### ISSUE TITLE
SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by 3lixy** [erming/shout#695]
I tried to join the default irc free node. Clicking connect results in the below:

```
/usr/local/lib/node_modules/shout/node_modules/request/node_modules/hawk/node_modules/boom/lib/index.js:5
const Hoek = require('hoek');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/shout/node_modules/request/node_modules/hawk/lib/index.js:5:33)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

default ocnfig was changed to run on port 9005.
one user was added

```
$ nodejs --version
v0.10.29

$ shout -v
0.53.0

$ uname -a
Linux revo-vpn-74 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1+deb8u1 (2017-02-22) x86_64 GNU/Linux

$ cat /etc/*release*
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by 3lixy** [comment]
I had installed nodejs (not legacy) so i removed nodjs and then installed nodejs-legacy and some other stuff;

```
sudo apt-get remove nodejs npm

sudo apt-get install nodejs-legacy npm

npm cache clean -f
npm WARN using --force I sure hope you know what you are doing.

sudo npm install -g n
/usr/local/bin/n -> /usr/local/lib/node_modules/n/bin/n
n@2.1.8 /usr/local/lib/node_modules/n

sudo n stable
     install : node-v9.2.0
       mkdir : /usr/local/n/versions/node/9.2.0
       fetch : https://nodejs.org/dist/v9.2.0/node-v9.2.0-linux-x64.tar.gz
######################################################################## 100.0%
   installed : v9.2.0

sudo npm install -g shout
shout start
```

**Comment by astorije** [comment]
Hey @3lixy!
Shout is currently inactive, so I recommend you to take a look at [The Lounge](https://github.com/thelounge/lounge), a fork of Shout that was started some time ago that is under active development.
Note however that it is not compatible with Node v0.10 and v0.12, so you'd have to use v4 or more recent (I'd recommend using v8).

Good luck!

**Comment by 3lixy** [comment]
Yes I already found that out and now am using The Lunge.
